In [1]:
#Importando as funções chi2_contingency porque temos 2 categorias
import numpy as np
from scipy.stats import chi2_contingency

In [2]:
# Criação da matriz com os dados e execução do teste
novela = np.array([[19, 6], [43, 32]])
novela

array([[19,  6],
       [43, 32]])

In [3]:
# Segundo valor é o pvolante
# Valor de p é maior que 0,05 não há evidências de diferença significativa (hipotese nula): não há diferença significativa
chi2_contingency(novela)

(2.037351443123939,
 0.15347667161786666,
 1,
 array([[15.5,  9.5],
        [46.5, 28.5]]))

In [4]:
novela2 = np.array([[22, 3], [43, 32]])
novela2

array([[22,  3],
       [43, 32]])

In [5]:
# Agora valor de p menor que 0.05, podemos rejeitar a hipotese nula em favor da hipotese alternativa
#  há diferença significativa
chi2_contingency(novela2)

(6.461538461538461,
 0.011023416388221425,
 1,
 array([[16.25,  8.75],
        [48.75, 26.25]]))